import type { ComponentType, MiniAppNode } from "@/mini-app/types/mini-app.types";

export type ComponentDefinition = {
  type: ComponentType;
  label: string;
  category: "layout" | "typography" | "forms" | "media" | "feedback" | "interactive";
  icon: string;
  canHaveChildren: boolean;
  defaultProps: Record<string, unknown>;
  defaultStyle?: Record<string, unknown>;
  minEditorSize?: {
    width?: number;
    height?: number;
  };
};

export const componentRegistry: Record<ComponentType, ComponentDefinition> = {
  container: {
    type: "container",
    label: "Container",
    category: "layout",
    icon: "square",
    canHaveChildren: true,
    defaultProps: {},
    defaultStyle: {
      direction: "vertical",
      alignItems: "stretch",
      justifyContent: "start",
      flex: undefined,
      position: "relative",
      gap: 12,
      padding: 16,
      backgroundColor: "#ffffff",
      borderRadius: 12,
    },
    minEditorSize: { height: 80 },
  },
  row: {
    type: "row",
    label: "Row",
    category: "layout",
    icon: "rows",
    canHaveChildren: true,
    defaultProps: {},
    defaultStyle: {
      direction: "horizontal",
      gap: 8,
      padding: 8,
      alignItems: "center",
      justifyContent: "start",
      flexWrap: "nowrap",
      backgroundColor: "transparent",
      borderRadius: 0,
    },
    minEditorSize: { height: 56 },
  },
  column: {
    type: "column",
    label: "Column",
    category: "layout",
    icon: "columns",
    canHaveChildren: true,
    defaultProps: {},
    defaultStyle: {
      direction: "vertical",
      gap: 8,
      padding: 8,
      alignItems: "stretch",
      justifyContent: "start",
      backgroundColor: "transparent",
      borderRadius: 0,
    },
    minEditorSize: { height: 72 },
  },
  scrollArea: {
    type: "scrollArea",
    label: "Scroll Area",
    category: "layout",
    icon: "scroll",
    canHaveChildren: true,
    defaultProps: {
      direction: "vertical",
      showScrollIndicator: true,
    },
    defaultStyle: {
      height: 200,
      padding: 8,
      backgroundColor: "transparent",
    },
    minEditorSize: { height: 160 },
  },
  text: {
    type: "text",
    label: "Text",
    category: "typography",
    icon: "text",
    canHaveChildren: false,
    defaultProps: {
      text: "Text Content",
      numberOfLines: undefined,
    },
    defaultStyle: {
      fontSize: 16,
      color: "#111827",
      fontWeight: "400",
      fontStyle: "normal",
      textAlign: "left",
      textDecoration: "none",
    },
  },
  heading: {
    type: "heading",
    label: "Heading",
    category: "typography",
    icon: "heading",
    canHaveChildren: false,
    defaultProps: {
      text: "Heading Content",
      level: 1,
    },
    defaultStyle: {
      fontSize: 24,
      fontWeight: "700",
      color: "#111827",
      textAlign: "left",
    },
  },
  button: {
    type: "button",
    label: "Button",
    category: "forms",
    icon: "button",
    canHaveChildren: false,
    defaultProps: {
      label: "Button",
      variant: "default",
      size: "default",
      disabled: false,
      loading: false,
      icon: "",
      iconPosition: "left",
    },
    defaultStyle: {
      backgroundColor: "#2563eb",
      textColor: "#ffffff",
      borderRadius: 10,
      padding: 12,
      minHeight: 44,
      fontSize: 14,
      fontWeight: "600",
      textAlign: "center",
    },
  },
  input: {
    type: "input",
    label: "Input",
    category: "forms",
    icon: "input",
    canHaveChildren: false,
    defaultProps: {
      placeholder: "Enter text",
      defaultValue: "",
      inputType: "text",
      secureTextEntry: false,
      disabled: false,
      required: false,
      maxLength: undefined,
      keyboardType: "default",
      autoCapitalize: "none",
    },
    defaultStyle: {
      backgroundColor: "#ffffff",
      textColor: "#000000",
      placeholderColor: "#94a3b8",
      borderColor: "#cbd5e1",
      borderWidth: 1,
      borderRadius: 10,
      padding: 12,
      minHeight: 44,
      fontSize: 14,
    },
  },
  textarea: {
    type: "textarea",
    label: "Textarea",
    category: "forms",
    icon: "textarea",
    canHaveChildren: false,
    defaultProps: {
      placeholder: "Type your message here.",
      defaultValue: "",
      numberOfLines: 4,
      maxLength: undefined,
      disabled: false,
      required: false,
    },
    defaultStyle: {
      backgroundColor: "#ffffff",
      textColor: "#000000",
      placeholderColor: "#94a3b8",
      borderColor: "#cbd5e1",
      borderWidth: 1,
      borderRadius: 10,
      padding: 12,
      minHeight: 88,
      fontSize: 14,
    },
  },
  image: {
    type: "image",
    label: "Image",
    category: "media",
    icon: "image",
    canHaveChildren: false,
    defaultProps: {
      sourceUrl: "",
      alt: "Image illustration",
    },
    defaultStyle: {
      width: 280,
      height: 160,
      borderRadius: 10,
      resizeMode: "cover",
      opacity: 1,
    },
  },
  card: {
    type: "card",
    label: "Card",
    category: "layout",
    icon: "card",
    canHaveChildren: true,
    defaultProps: {
      title: "Card Title",
      description: "Card Description",
      shadow: true,
    },
    defaultStyle: {
      backgroundColor: "#ffffff",
      borderColor: "#e4e4e7",
      borderWidth: 1,
      borderRadius: 12,
      padding: 16,
      gap: 12,
    },
    minEditorSize: { height: 120 },
  },
  badge: {
    type: "badge",
    label: "Badge",
    category: "typography",
    icon: "badge",
    canHaveChildren: false,
    defaultProps: {
      text: "Badge",
      variant: "default",
    },
    defaultStyle: {
      borderRadius: 9999,
      padding: 6,
      fontSize: 12,
      fontWeight: "600",
    },
  },
  checkbox: {
    type: "checkbox",
    label: "Checkbox",
    category: "forms",
    icon: "checkbox",
    canHaveChildren: false,
    defaultProps: {
      label: "Accept terms",
      checked: false,
      defaultChecked: false,
      disabled: false,
      required: false,
    },
    defaultStyle: {
      checkedColor: "#0f172a",
      labelColor: "#000000",
      size: 16,
    },
  },
  switch: {
    type: "switch",
    label: "Switch",
    category: "forms",
    icon: "switch",
    canHaveChildren: false,
    defaultProps: {
      label: "Enable notifications",
      checked: false,
      defaultValue: false,
      disabled: false,
    },
    defaultStyle: {
      activeColor: "#10b981",
      inactiveColor: "#e4e4e7",
      thumbColor: "#ffffff",
    },
  },
  separator: {
    type: "separator",
    label: "Separator",
    category: "layout",
    icon: "separator",
    canHaveChildren: false,
    defaultProps: {
      orientation: "horizontal",
    },
    defaultStyle: {
      thickness: 1,
      color: "#e4e4e7",
    },
  },
  radioGroup: {
    type: "radioGroup",
    label: "Radio Group",
    category: "forms",
    icon: "radio",
    canHaveChildren: false,
    defaultProps: {
      label: "Radio Label",
      options: "Option A\nOption B\nOption C",
      selectedValue: "Option A",
    },
    defaultStyle: {},
  },
  accordion: {
    type: "accordion",
    label: "Accordion",
    category: "interactive",
    icon: "accordion",
    canHaveChildren: true,
    defaultProps: {
      title: "Accordion Item",
      description: "Accordion Content description.",
      allowMultiple: false,
      defaultOpenItem: "",
    },
    defaultStyle: {
      backgroundColor: "#ffffff",
      borderColor: "#e4e4e7",
      borderRadius: 8,
      titleColor: "#3f3f46",
      contentColor: "#71717a",
    },
    minEditorSize: { height: 96 },
  },
  tabs: {
    type: "tabs",
    label: "Tabs",
    category: "interactive",
    icon: "tabs",
    canHaveChildren: true,
    defaultProps: {
      tabs: "Tab 1\nTab 2",
      defaultTab: "Tab 1",
      activeTab: "Tab 1",
      orientation: "horizontal",
    },
    defaultStyle: {
      activeColor: "#18181b",
      inactiveColor: "#71717a",
      backgroundColor: "#f4f4f5",
      indicatorColor: "#18181b",
    },
    minEditorSize: { height: 112 },
  },
  progress: {
    type: "progress",
    label: "Progress",
    category: "feedback",
    icon: "progress",
    canHaveChildren: false,
    defaultProps: {
      value: 60,
      min: 0,
      max: 100,
      showValue: false,
    },
    defaultStyle: {
      backgroundColor: "#f4f4f5",
      progressColor: "#18181b",
      borderRadius: 9999,
      height: 10,
    },
  },
  avatar: {
    type: "avatar",
    label: "Avatar",
    category: "media",
    icon: "avatar",
    canHaveChildren: false,
    defaultProps: {
      sourceUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100",
      fallbackText: "CN",
    },
    defaultStyle: {
      size: 40,
      borderRadius: 20,
    },
  },
  alert: {
    type: "alert",
    label: "Alert",
    category: "feedback",
    icon: "alert",
    canHaveChildren: false,
    defaultProps: {
      title: "Alert Title",
      description: "Alert Description",
      variant: "default",
      icon: "info",
      dismissible: false,
    },
    defaultStyle: {
      borderRadius: 8,
      borderWidth: 1,
    },
  },
  skeleton: {
    type: "skeleton",
    label: "Skeleton",
    category: "feedback",
    icon: "skeleton",
    canHaveChildren: false,
    defaultProps: {},
    defaultStyle: {
      width: 200,
      height: 20,
      borderRadius: 4,
      opacity: 0.5,
    },
  },
  slider: {
    type: "slider",
    label: "Slider",
    category: "forms",
    icon: "slider",
    canHaveChildren: false,
    defaultProps: {
      min: 0,
      max: 100,
      step: 1,
      defaultValue: 50,
      disabled: false,
    },
    defaultStyle: {
      trackColor: "#e4e4e7",
      activeTrackColor: "#18181b",
      thumbColor: "#ffffff",
    },
  },
  aspectRatio: {
    type: "aspectRatio",
    label: "Aspect Ratio",
    category: "layout",
    icon: "aspect",
    canHaveChildren: true,
    defaultProps: {
      ratio: 1.77,
    },
    defaultStyle: {},
    minEditorSize: { height: 120 },
  },
  label: {
    type: "label",
    label: "Label",
    category: "typography",
    icon: "label",
    canHaveChildren: false,
    defaultProps: {
      text: "Form Label",
      required: false,
      targetInputId: "",
    },
    defaultStyle: {
      fontSize: 14,
      fontWeight: "500",
      color: "#374151",
    },
  },
  pagination: {
    type: "pagination",
    label: "Pagination",
    category: "interactive",
    icon: "pagination",
    canHaveChildren: false,
    defaultProps: {
      currentPage: 1,
      totalPages: 5,
      showEllipsis: true,
    },
    defaultStyle: {
      gap: 8,
      padding: 8,
      alignment: "center",
    },
  },
  list: {
    type: "list",
    label: "List",
    category: "typography",
    icon: "list",
    canHaveChildren: false,
    defaultProps: {
      title: "List Title",
      items: "Item 1\nItem 2\nItem 3",
      ordered: false,
      showDividers: false,
    },
    defaultStyle: {
      fontSize: 14,
      color: "#111827",
      fontWeight: "400",
      gap: 8,
      padding: 0,
      margin: 0,
    },
  },
};

export function createDefaultNode(type: ComponentType, id: string): MiniAppNode {
  const definition = componentRegistry[type];

  return {
    id,
    type,
    props: { ...definition.defaultProps },
    style: { ...definition.defaultStyle },
    children: definition.canHaveChildren ? [] : undefined,
  };
}
